---
title: "Dissertation_coding_YBJM3"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#PRELIMINARIES
```


```{r}
# Setting my working directory
setwd("~/Desktop/Dissertation Coding")

# Emptying the environment
rm(list=ls()) 

# Loading the packages necessary 
library(readr)
library(readxl)
library(haven)
library(texreg)
library(ggplot2)
library(dplyr)
library(plyr)
library(stargazer)
library(tidyr)
library(estimatr)
library(gridExtra)
```


```{r}
# BUILDING THE DATASET
```


```{r}
# Gathering data from the World Bank (2022)

# Installing the latest version of the wbstats R-package to get data from the World Bank API.
install.packages("wbstats")
# Installing the latest development version for the package from github 
devtools::install_github("nset-ornl/wbstats")
# Accessing updated available data
library(wbstats)
sr(wb_cachelist, max.level = 1)

# Creating a dataframe with the variables I am interested in 
wdi_df <- wb_data(
  country = "countries_only",
  indicator = c("general_public_expenditures" = "NE.CON.GOVT.ZS", "Oil_rents_%_of_GDP" = "NY.GDP.PETR.RT.ZS", "Coal_rents_%_of_GDP" = "NY.GDP.COAL.RT.ZS", "Natural_gas_rents_%_of_GDP" = "NY.GDP.NGAS.RT.ZS", "Electricity_production_from_oil_gas_coal" = "EG.ELC.FOSL.ZS", "Inflation" = "NY.GDP.DEFL.KD.ZG")) 

# Creating another dataframe with only the countries I am interested in 
world_bank_data <-  subset(wdi_df, country %in% c("Australia" , "Austria" , "Belgium", "Canada", "Denmark", "Finland", "France", "Germany", "Greece",  "Ireland", "Italy", "Japan", "Netherlands", "New Zealand", "Norway", "Portugal", "Spain", "Sweden", "United Kingdom", "United States"))

# Creating another dataframe that includes only the years I am interested in 
world_bank <-  subset(world_bank_data, date %in% c("1990" , "1991" , "1992", "1993", "1994", "1995", "1996", "1997", "1998",  "1999", "2000", "2001", "2002", "2003", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010"))

# Exporting the dataset into a csv file
write.csv(CPDS_data , "~/Desktop/Dissertation Coding/WorldBankData.csv", row.names=FALSE)
```


```{r}
# Selecting data from the Comparative Political Data Set (Armingeon et al., 2022)

# Importing and re-naming the dataset
CPDS <- read_dta("~/Desktop/Dissertation Coding/Data/CPDS_2022.dta") # file path 
View(CPDS)

# Creating a dataframe with the relevant variables
CPDS_df <-  subset(CPDS[ ,c("country", "year", "prop" , "fed", "pres", "bic", "deficit", "instcons", "elect", "socexp_t_pmp", "eu" )])

# Creating a dataframe with the relevant countries 
CPDS_data <- subset(CPDS_df, country %in% c("Australia" , "Austria" , "Belgium", "Canada", "Denmark", "Finland", "France", "Germany", "Greece",  "Ireland", "Italy", "Japan", "Netherlands", "New Zealand", "Norway", "Portugal", "Spain", "Sweden", "United Kingdom", "USA"))

# Subsetting the dataframe to include only the relevant years 
CPDS_data  <-  subset(CPDS_data, year %in% c("1990" , "1991" , "1992", "1993", "1994", "1995", "1996", "1997", "1998",  "1999", "2000", "2001", "2002", "2003", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010"))

# Exporting the dataset into a csv file
write.csv(CPDS_data , "~/Desktop/Dissertation Coding/CPDS_dataNEW.csv", row.names=FALSE) # file path
```


```{r}
# Selecting data from Finnegan's (2022a) dataset

# Importing and re-naming the dataset
Finnegan_2022a <- read_dta("~/Desktop/Dissertation Coding/Data/Finnegan_2022a.dta") # file path 
View(Finnegan_2022a)

# Creating a dataframe with the relevant variables 
Finnegan_a <-  subset(Finnegan_2022a[ ,c("countryname", "countryid", "year" ,"ja20f_v2", "ja10f")])

# Subsetting the dataframe to include only the relevant countries
Finnegan_a <- subset(Finnegan_a, countryname %in% c("Australia" , "Austria" , "Belgium", "Canada", "Denmark", "Finland", "France", "Germany", "Greece",  "Ireland", "Italy", "Japan", "Netherlands", "New Zealand", "Norway", "Portugal", "Spain", "Sweden", "United Kingdom", "United States"))

# Subsetting the dataframe to include only the relevant years 
Finnegan_a <-  subset(Finnegan_a, year %in% c("1990" , "1991" , "1992", "1993", "1994", "1995", "1996", "1997", "1998",  "1999", "2000", "2001", "2002", "2003", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010"))

# Exporting the dataset into a csv file
write.csv(Finnegan_a, "~/Desktop/Dissertation Coding/Finnegan_a.csv", row.names=FALSE) # file path
```


```{r}
# Selecting data from Finnegan's (2022b) dataset

# Importing and re-naming the dataset
Finnegan_2022b <- read_dta("~/Desktop/Dissertation Coding/Data/Finnegan_2022b.dta")
View(Finnegan_2022b) # file path 

# Creating a dataframe with the relevant variables 
Finnegan_b <-  subset(Finnegan_2022b[ ,c("country_num", "year" ,"per501_avg", "elect_year", "green_cab", "left_incum", "single_party")])

# Subsetting the dataframe to include only the relevant years 
Finnegan_b <-  subset(Finnegan_a, year %in% c("1990" , "1991" , "1992", "1993", "1994", "1995", "1996", "1997", "1998",  "1999", "2000", "2001", "2002", "2003", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010"))

# Exporting the dataset into a csv file
write.csv(Finnegan_b, "~/Desktop/Dissertation Coding/Finnegan_b.csv", row.names=FALSE) # file path 
```


```{r}
# FINALISING THE DATASET
```


```{r}
# Manually combining the raw data into my final dataset

# Importing and re-naming my final dataset
dataset <- read_delim("~/Desktop/Dissertation Coding/POLS0086 DATASET YBJM3.csv", #file path
    delim = ";", escape_double = FALSE, trim_ws = TRUE) 
View(dataset)

# Lagging the 'deficit' variable by one year
countries <- levels(as.factor(dataset$CountryName))
data <- dataset[dataset$CountryName == countries[1],]
for (i in countries) {
  dat <-dataset[dataset$CountryName == i,]
  dat$deficit<-lag(dat$deficit)
 data<- rbind(data,dat)
}
data<-data[22:nrow(data),]
dim(data)

# I extract data for year 1989 from the Comparative Political Data Set (Armingeon et al., 2022) in order to not have any missing data in my lagged variable 

# Importing and naming the dataset
CPDS <- read_dta("~/Desktop/Dissertation Coding/Data/CPDS_2022.dta") # file path in the directory where the CPDS dataset is saved

# Creating a dataframe with the relevant countries 
CPDS_data <- subset(CPDS, country %in% c("Australia" , "Austria" , "Belgium", "Canada", "Denmark", "Finland", "France", "Germany", "Greece",  "Ireland", "Italy", "Japan", "Netherlands", "New Zealand", "Norway", "Portugal", "Spain", "Sweden", "United Kingdom", "USA"))

# Creating a dataframe with the relevant year 
CPDS_df  <-  subset(CPDS_data, year %in% c("1989"))

# Subsetting the dataframe to include only the 'deficit' variable
CPDS_df <-  subset(CPDS_df[ ,c("deficit")])

# Imputing the data in my dataset manually for each country
data[1, 29] <- 0.464548242201381 # Australia 
data[22, 29] <- -3.28532379288354 # Austria
data[43, 29] <- -7.54951715701853 # Belgium
data[64, 29] <- -4.71828332928814 # Canada
data[85, 29] <- -0.255719813506534 # Denmark
data[106, 29] <- 6.73331469865831 # Finland
data[127, 29] <- -1.78164319013484 # France
data[148, 29] <- 0.08081086 # Germany
data[169, 29] <- -12.14489149 # Greece
data[190, 29] <- -2.649669945 # Ireland
data[211, 29] <- -10.9976147487809 # Italy
data[232, 29] <- 1.39539049396472 # Japan
data[253, 29] <- -4.42222927286664 # Netherlands
data[274, 29] <- -3.60985366302392 # New Zealand
data[295, 29] <- 1.8285410324526 # Norway
data[316, 29] <- -2.56472804047965 # Portugal
data[337, 29] <- -3.5767310963607 # Spain
data[358, 29] <- 3.04443216902729 # Sweden
data[379, 29] <- 0.0499085551717129 # United Kingdom
data[400, 29] <- -4.47666739429976 # USA
```


```{r}
# ANALYSIS
```


```{r}
# MODEL 1:
# Regressing disproportionality on low-carbon R&D with time fixed-effects but without controls
reg1 <- lm(lowcarbonRDexp ~ disproportionality + factor(year), data=dataset)
# Printing the regression's output in a table
screenreg(reg1)

# Calculating the country-level robust SEs with the estimatr() specifying country-level clusters and the 'stata' method for cluster-robust SEs
lmclust1 <- lm_robust(lowcarbonRDexp ~ disproportionality, data=dataset, clusters = CountryName, fixed_effects =~year, se_type = "stata")
# Printing the regression's output in tables
summary(lmclust1)
screenreg(lmclust1)
tidy(lmclust1)

# MODEL 2:
# Regressing disproportionality on low-carbon R&D with time fixed-effects and a parsimonious set of controls
reg2 <- lm(lowcarbonRDexp ~ disproportionality + factor(year) + green_vs_growth + left_vs_right + green_cabinet + deficit + political_constraints + Coal_rents_percentage_of_GDP + Natural_gas_rents_percentage_of_GDP + Oil_rents_percentage_of_GDP, data=data)
# Printing the regression's output in a table
screenreg(reg2)

# Calculating the country-level robust SEs with the estimatr() specifying year FE, country-level clusters and the 'stata' method for cluster-robust SEs
lmclust2 <- lm_robust(lowcarbonRDexp ~ disproportionality + green_vs_growth + left_vs_right + green_cabinet + deficit + political_constraints + Coal_rents_percentage_of_GDP + Natural_gas_rents_percentage_of_GDP + Oil_rents_percentage_of_GDP, data=data, fixed_effects = ~year, clusters = CountryName, se_type = "stata")
# Printing the regression's output in tables
summary(lmclust2)
screenreg(lmclust2)
tidy(lmclust2)

# MODEL 3:
# Regressing disproportionality on low-carbon R&D with time fixed-effects and additional controls 
reg3 <- lm(lowcarbonRDexp ~ disproportionality + factor(year) + green_vs_growth + green_cabinet + left_vs_right + left_incumbent_gov +  election_year + EU + bic + pres + fed + Inflation + political_constraints + social_expenditures + general_public_expenditures + environmental_saliency + institutional_constraints + deficit + Coal_rents_percentage_of_GDP + Natural_gas_rents_percentage_of_GDP + Oil_rents_percentage_of_GDP + Electricity_production_from_oil_gas_coal + deficit, data=dataset)
# Printing the regression's output in a table
screenreg(reg3)

# Calculating the country-level robust SEs with the estimatr() specifying year FE, country-level clusters and the 'stata' method for cluster-robust SEs
lmclust3 <- lm_robust(lowcarbonRDexp ~ disproportionality + green_vs_growth + green_cabinet + left_vs_right + left_incumbent_gov +  election_year + EU + bic + pres + fed + Inflation + political_constraints + social_expenditures + general_public_expenditures + environmental_saliency + institutional_constraints + deficit + Coal_rents_percentage_of_GDP + Natural_gas_rents_percentage_of_GDP + Oil_rents_percentage_of_GDP + Electricity_production_from_oil_gas_coal + deficit, data=dataset, fixed_effects = ~year, clusters = CountryName, se_type = "stata")
# Printing the regression's output in tables 
summary(lmclust3)
screenreg(lmclust3)
tidy(lmclust3)

# I want to use another estimate for proportionality, to check if my model's preformance varies: so, instead of using Lijphart's (2012) "disproportionality" measure, I am using the "prop" variable from the Comparative Political Data Set (Armingeon et al., 2022)

# Re-coding the "prop" variable into a dummy variable for proportional and majoritarian electoral systems obtained from the Comparative Political Data Set (Armingeon et al., 2022) 
# In the Comparative Political Data Set,  0 = majoritarian; 1 = mixed; 2 = proportional representation (PR)

# I re-code the variable into: 0 = majoritarian (majoritarian & mixed); 1 = proportional representation (PR) and impute it into my dataset
data$proportional <- mapvalues(dataset$prop, from = c("0", "1", "2"), to = c("0", "0", "1"))

# MODEL 4:
# Regressing the dummy variable for PR rules on low-carbon R&D with time fixed-effects and a parsimonious set of controls 
reg4 <- lm(lowcarbonRDexp~ proportional + factor(year) + green_vs_growth + left_vs_right + green_cabinet + political_constraints + deficit + Coal_rents_percentage_of_GDP + Natural_gas_rents_percentage_of_GDP + Oil_rents_percentage_of_GDP, data=data)
# Printing the regression's output in a table
screenreg(reg4)

# Calculating the country-level robust SEs with the estimatr() specifying year FE, country-level clusters and the 'stata' method for cluster-robust SEs
lmclust4 <- lm_robust(lowcarbonRDexp ~ proportional + green_vs_growth + left_vs_right + green_cabinet + political_constraints + deficit + Coal_rents_percentage_of_GDP + Natural_gas_rents_percentage_of_GDP + Oil_rents_percentage_of_GDP, data=data, fixed_effects= ~year, clusters = CountryName, se_type = "stata")
# Printing the regression's output in tables 
screenreg(lmclust4)
summary(lmclust4)
tidy(lmclust4)

# MODEL 5: 
# Regressing the dummy variable for PR rules on low-carbon R&D with time fixed-effects and additional controls
reg5 <- lm(lowcarbonRDexp~ proportional + factor(year) +  green_vs_growth + green_cabinet + left_vs_right + left_incumbent_gov +  election_year + EU + bic + pres + fed + Inflation + social_expenditures + general_public_expenditures + environmental_saliency + institutional_constraints + political_constraints + deficit + Coal_rents_percentage_of_GDP + Natural_gas_rents_percentage_of_GDP + Oil_rents_percentage_of_GDP + Electricity_production_from_oil_gas_coal + deficit , data=data)
screenreg(reg5)

# Calculating the country-level robust SEs with the estimatr() specifying year FE, country-level clusters and the 'stata' method for cluster-robust SEs
lmclust5 <- lm_robust(lowcarbonRDexp ~ proportional +  green_vs_growth + green_cabinet + left_vs_right + left_incumbent_gov +  election_year + EU + bic + pres + fed + Inflation + social_expenditures + general_public_expenditures + environmental_saliency + institutional_constraints + political_constraints + deficit + Coal_rents_percentage_of_GDP + Natural_gas_rents_percentage_of_GDP + Oil_rents_percentage_of_GDP + Electricity_production_from_oil_gas_coal + deficit , data=data, fixed_effects = ~ year, clusters = CountryName, se_type = "stata")
# Printing the regression's output in tables 
summary(lmclust5)
screenreg(lmclust5)
tidy(lmclust5)

# Converting all regressions' output into a table and exporting it
all_models <- screenreg(list(lmclust1, lmclust2, lmclust3, lmclust4, lmclust5), custom.model.names = c("Model 1","Model 2","Model 3", "Model 4","Model 5"), digits=3)
all_models

# Exporting the table into a txt file
write.table(all_models, file = "table!.txt", sep = ",", quote = FALSE, row.names = F)
```

```{r}
# GRAPHS
```


```{r}
# Figure A.6

# Subsetting the dataset to create a bar graph of electoral disproportionality per country 
plot_dataset <- subset(dataset[, c("...1","CountryName", "year", "disproportionality")])
plot_data <- subset(plot_dataset, year %in% "1990")

# Creating the barplot
barplot_data <- data.frame(x_axis = plot_dataset$CountryName, y_axis=plot_dataset$disproportionality)
ggp  <- ggplot(barplot_data, aes(x_axis, y_axis)) +
  geom_bar(stat = "identity", width=0.6, fill="steelblue") +
  theme_minimal() + ylab("Electoral disproportionality (Lijphart, 2012)") + xlab("Country") +  ggtitle("Electoral disproportionality per country")
ggp + coord_flip()
```


```{r}
# I have manually calculated the average values for some variables (low-carbon R&D expenditure, disproportionality, political constraints, EU membership and the percentage of green cabinet seats) in Excel and saved the file in csv format

# Importing and re-naming the dataset 
d <- read_delim("~/Desktop/Dissertation Coding/POLS0086_DATA_YBJM3.csv", 
    delim = ";", escape_double = FALSE, col_types = cols(average_low_carbon_RD_spending = col_number(), 
        disproportionality = col_number()), 
    trim_ws = TRUE)
```


```{r}
# Figure 1

# Creating a scatter plot of disproportionality and average low-carbon R&D expenditure
plot <- ggplot(d, aes(x = disproportionality, y = average_low_carbon_RD_spending)) +
  geom_point(size=2) +  geom_text(hjust = 0.2, vjust=2, nudge_x = 0.3, size=2, aes(label = Country)) + geom_smooth(method="lm", se=F, fullrange=FALSE, level=0.95, color="black") + stat_poly_eq(use_label(c("R2"))) + labs(title = "Electoral disproportionality and low-carbon R&D expenditure", x = "Electoral disproportionality", y = "Avarage low-carbon R&D expenditure") + theme_bw() + theme(plot.title = element_text(hjust = 0.5))
plot
```


```{r}
# Figure A.1

# Creating a scatter plot of disproportionality and average low-carbon R&D expenditure based on political constraints
scatter <- ggplot(d, aes(x = disproportionality, y = average_low_carbon_RD_spending, color = political_constraints)) +
  geom_point(size=2) +  geom_text(hjust = 0.2, vjust=2, nudge_x = 0.3, size=2, aes(label = Country)) + geom_smooth(method="lm", se=F, fullrange=FALSE, level=0.95, color="black", aes(color = political_constraints, scale_shape_binned= green_cabinet)) + stat_poly_eq(use_label(c("R2"))) + labs(title = "Electoral disproportionality and average low-carbon R&D expenditure based on political constraints", x = "Electoral disproportionality", y = "Avarage low-carbon R&D expenditure across 1990-2010", color="Political constraints") + theme_bw() + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.title = element_text(size=9), axis.title.x = element_text(size = 9), axis.title.y = element_text(size = 9), legend.text=element_text(size=8), legend.title =element_text(size=9))
scatter
```


```{r}
# Figure A.2

# Creating a scatter plot of disproportionality and average low-carbon R&D expenditure based on percentage of 'green' cabinet seats
scatterplot <- ggplot(d, aes(x = disproportionality, y = average_low_carbon_RD_spending, color = green_cabinet)) + geom_point(size=2) +  geom_text(hjust = 0.2, vjust=2, nudge_x = 0.3, size=2, aes(label = Country)) + geom_smooth(method="lm", se=F, fullrange=FALSE, level=0.95, color="black", aes(color = green_cabinet)) + stat_poly_eq(use_label(c("R2"))) + labs(title = "Electoral disproportionality and average low-carbon R&D expenditure based on percentage of 'green' cabinet seats", x = "Electoral disproportionality", y = "Avarage low-carbon R&D expenditure across 1990-2010", color="Percentage of cabinet seats held by 'green' parties") + theme_bw() + theme(plot.title = element_text(size=9), axis.title.x = element_text(size = 9), axis.title.y = element_text(size = 9), legend.text=element_text(size=8), legend.title =element_text(size=9))
scatterplot
```


```{r}
# Figure A.3

# Creating a scatter plot of disproportionality and average low-carbon R&D expenditure based on EU membership
scat <- ggplot(d, aes(x = disproportionality, y = average_low_carbon_RD_spending,  color=EU)) +
  geom_point(size=2) +  geom_text(hjust = 0.2, vjust=2, nudge_x = 0.3, size=2, aes(label = Country)) + geom_smooth(method="lm", se=F, fullrange=FALSE, level=0.95, color="black", aes(size=EU)) + stat_poly_eq(use_label(c("R2"))) + labs( title = "Electoral disproportionality and average low-carbon R&D expenditure based on EU membership", x = "Electoral disproportionality", y = "Avarage low-carbon R&D expenditure across 1990-2010", color="EU Membership") + theme_bw() + theme(plot.title = element_text(size=9), axis.title.x = element_text(size = 9), axis.title.y = element_text(size = 9), legend.text=element_text(size=8), legend.title =element_text(size=9))
scat
```


```{r}
# Figure A.6

# Arranging the disproportionality values in descending order
d_sorted <- arrange(d, desc(Country))
# Creating a bar plot of electoral disproportionality per country 
ggplot(d_sorted, aes(x = Country, y = disproportionality)) + geom_bar(stat = "identity", width=0.6) + coord_flip() + labs(title = "Electoral disproportionality per country", x = "Country", y = "Electoral disproportionality (Lijphart, 2012)") + theme_bw()
```

```{r}
# Figure A.5

# Creating plots for country trends in low-carbon R&D expenditure across 1990-2010

# Subsetting the data to focus on Australia first
dataAustralia <- subset(data, CountryName %in% c("Australia"))
# Creating my plot
plot1 <- ggplot(dataAustralia, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Australia") + theme_bw()+ theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Austria and creating the plot
dataAustria <- subset(data, CountryName %in% c("Austria"))
plot2 <- ggplot(dataAustria, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Austria") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Belgium and creating the plot
dataBelgium <- subset(data, CountryName %in% c("Belgium"))
plot3 <- ggplot(dataBelgium, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Belgium") + theme_bw()+ theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Canada and creating the plot
dataCanada <- subset(data, CountryName %in% c("Canada"))
plot4 <- ggplot(dataCanada, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Canada") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Denmark and creating the plot
dataDenmark <- subset(data, CountryName %in% c("Denmark"))
plot5 <- ggplot(dataDenmark, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Denmark") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Finland and creating the plot
dataFinland <- subset(data, CountryName %in% c("Finland"))
plot6 <- ggplot(dataFinland, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Finland") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on France and creating the plot
dataFrance <- subset(data, CountryName %in% c("France"))
plot7 <- ggplot(dataFrance, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "France") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Germany and creating the plot
dataGermany <- subset(data, CountryName %in% c("Germany"))
plot8 <- ggplot(dataGermany, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Germany") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Greece and creating the plot
dataGreece <- subset(data, CountryName %in% c("Greece"))
plot9 <- ggplot(dataGreece, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Greece") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Ireland and creating the plot
dataIreland <- subset(data, CountryName %in% c("Ireland"))
plot10 <- ggplot(dataIreland, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Ireland") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))
                                                                                                                    
# Subsetting the data to focus on Italy and creating the plot
dataItaly <- subset(data, CountryName %in% c("Italy"))
plot11 <- ggplot(dataItaly, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Italy") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Japan and creating the plot
dataJapan <- subset(data, CountryName %in% c("Japan"))
plot12 <- ggplot(dataJapan, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Japan") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Netherlands and creating the plot
dataNetherlands <- subset(data, CountryName %in% c("Netherlands"))
plot13 <- ggplot(dataNetherlands, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Netherlands") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on New Zealand and creating the plot
dataNewZealand <- subset(data, CountryName %in% c("New Zealand"))
plot14 <- ggplot(dataNewZealand, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "New Zealand") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Norway and creating the plot
dataNorway <- subset(data, CountryName %in% c("Norway"))
plot15 <- ggplot(dataNorway, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Norway") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Portugal and creating the plot
dataPortugal <- subset(data, CountryName %in% c("Portugal"))
plot16 <- ggplot(dataPortugal, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Portugal") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Spain and creating the plot
dataSpain <- subset(data, CountryName %in% c("Spain"))
plot17 <- ggplot(dataSpain, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Spain") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on Sweden and creating the plot
dataSweden <- subset(data, CountryName %in% c("Sweden"))
plot18 <- ggplot(dataSweden, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "Sweden") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on the United Kingdom and creating the plot
dataUK <- subset(data, CountryName %in% c("United Kingdom"))
plot19 <- ggplot(dataUK, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "United Kingdom") + theme_bw()+ theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Subsetting the data to focus on the United States and creating the plot
dataUS <- subset(data, CountryName %in% c("United States"))
plot20 <- ggplot(dataUS, aes(x = year, y = lowcarbonRDexp)) +
  geom_line() +
  labs(x = "Time", y = "Low-carbon R&D expenditure", title = "United States") + theme_bw() + theme(plot.title = element_text(size=5), axis.title.x = element_text(size = 4), axis.title.y = element_text(size = 4)) + ylim(0,6) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(size = 4), axis.text.y = element_text(size = 4))

# Creating a table layout whereby my plots' panels are all on one page with 5 columns
grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8,plot9, plot10, plot11, plot12, plot13, plot14, plot15, plot16, plot17, plot18, plot19, plot20, ncol=5, top="Trends in low-carbon R&D expenditure across countries from 1990 to 2010")
```
```


```{r}
# SUMMARY STATISTICS
```

```{r}
# Table A.3

# Installing the vtable package 
install.packages("vtable")

# Loading the necessary libraries
library(kableExtra)
library(vtable)

# Getting basic summary stats
st(data, digits=4)
```